giantswarm/api-spec

README.md
definitions.yaml
parameters.yaml
redoc/index.html
spec.yaml

First version of Open API spec for v4 API

---

circle.yml
docserver/kubernetes/deployment.yaml

Related a bit to: https://github.com/giantswarm/api-spec/pull/13

move images and pull secret to quay. use architect

---

parameters.yaml
spec.yaml

For https://github.com/giantswarm/giantswarm/issues/1123

Idempotency documentation and header spec

---

.gitignore
definitions.yaml
details/CLUSTER_DEFINITION.md
spec.yaml

For https://github.com/giantswarm/api-spec/issues/24

Spec/docs for scaling clusters (adding/removing cluster nodes)

---

definitions.yaml
spec.yaml

Related to: https://github.com/giantswarm/api-spec/issues/26

/v4/users/ - listing users

---

.gitignore
definitions.yaml
details/CLUSTER_DEFINITION.md
spec.yaml

Reverts giantswarm/api-spec#27

Revert "Spec/docs for scaling clusters (adding/removing cluster nodes)"

---

parameters.yaml
spec.yaml

This specs deleting users.
EDIT: something went wrong with my hub client, and it pushed this with an totally unrelated PR message)

Spec DELETE /v4/users/{email}/

---

README.md

This adds the quay container badge and link to the README

Adding Quay badge

---

circle.yml

Part of moving stuff from lycan to guest cluster on ginger

Push to registry since architect deploy don't do that no more

---

definitions.yaml
spec.yaml

Part of https://github.com/giantswarm/giantswarm/issues/2022

Selecting a release version when creating a cluster

---

definitions.yaml
spec.yaml

Part of https://github.com/giantswarm/giantswarm/issues/2022

Adding the release_version attribute to getCluster response

---

helm/api-spec-chart/templates/deployment.yaml

Setting revisionHistoryLimit

---

definitions.yaml
spec.yaml

Spec for https://github.com/giantswarm/api/issues/282
The goal here is to provide a first iteration of an info endpoint. The list of details doesn't have to contain everything we can think of, but is mostly informed by the use case we know about with certainty.
- The sub keys `min`, `max`, `default`, and `options` are part of a recurring scheme, however not all info entries can provide them.
- Authenticated vs. unauthenticated access: Do we want/have to expose some info details even to anonymous users?

Info endpoint

---

spec.yaml

Removing empty "parameters" key

---

.circleci/config.yml
spec.yaml

Remove OrganizationIdPathParameter

---

definitions.yaml
spec.yaml

Part of https://github.com/giantswarm/giantswarm/issues/2022

Adding release_version to the modifyCluster operation

---

Makefile
spec.yaml

This PR fixes a problem we had with the way the definitions and parameters file were referenced. It caused an error in swagger-codegen, which we use for validation and generating clients.

Fix references, improve Makefile

---

spec.yaml

Fix some minor typos in the documentation

Fix typos in docs

---

definitions.yaml
spec.yaml

https://github.com/giantswarm/giantswarm/issues/2192

Remove stuff we are not actually returning yet from the info spec.

---

definitions.yaml

Towards https://github.com/giantswarm/giantswarm/issues/2454

Add Azure vm_size for cluster creation (POST /v4/clusters/)

---

definitions.yaml
spec.yaml

To make this story a bit more concrete. RFC @marians @xh3b4sd
Already working on the `kubernetesd` part, but wanted to pause a bit and see if we are aligned for the final result of this, in terms of what will actually be added / changed in the API.
https://github.com/giantswarm/api-spec/issues/50

Spec the ingress ports addition.

---

definitions.yaml

Towards https://github.com/giantswarm/giantswarm/issues/2760.

adds release version to cluster lister response

---

definitions.yaml

Towards https://github.com/giantswarm/giantswarm/issues/2760.

fixes release version tag in response body

---

spec.yaml

Specs the `/v4/users/{email}/` endpoint.
Separated from: https://github.com/giantswarm/api-spec/pull/82
Part of: Part of: https://github.com/giantswarm/giantswarm/issues/2955

Add a spec for fetching info about a specific user. (/v4/users/{email}/)

---

definitions.yaml
spec.yaml

Having this in /v4/ will help us get closer to removing all legacy from API.

Add specs for creating / deleting auth tokens

---

definitions.yaml

Fix typo: auth_token

---

spec.yaml

Fix for https://github.com/giantswarm/api-spec/issues/78

Add request body schema to addOrganization spec

---

spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/3404

Add info in the auth token about expiration

---

spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/3596

Remove metrics endpoint

---

spec.yaml

Fixes https://github.com/giantswarm/giantswarm/issues/3622

Rephrase introduction on authentication

---

definitions.yaml
spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/4115.

adds idea about default provider worker count

---

definitions.yaml
spec.yaml

Reverts giantswarm/api-spec#112

Revert "adds idea about default provider worker count"

---

definitions.yaml
spec.yaml

Reverts giantswarm/api-spec#113

Revert "Revert "adds idea about default provider worker count""

---

.github/PULL_REQUEST_TEMPLATE.md

Towards https://github.com/orgs/giantswarm/projects/12#card-13911505

Add a simple template to remember us to inform our customers

---

definitions.yaml
spec.yaml

Support autoscaling of tenant clusters

---

DCO
LICENSE

Create LICENSE and DCO

---

definitions.yaml
docserver/index.html
spec.yaml

The purpose of this PR was to draft having v4 and v5 operations in parallel.
This is merged into https://github.com/giantswarm/api-spec/pull/130 after discussion

Node pools as v5

---

parameters.yaml
spec.yaml

Relatively straight forward, this adds a way to delete an app at `DELETE /v4/clusters/{cluster_id}/apps/{app_name}/`

Add spec for deleting apps.

---

Makefile
README.md
definitions.yaml
parameters.yaml
spec.yaml

This PR takes the accepted specs so far for the managed apps topic and groups in one place.
`GET /v4/appcatalogs/` https://github.com/giantswarm/api-spec/pull/131
`GET /v4/clusters/:clusterid/apps/` https://github.com/giantswarm/api-spec/pull/132
`PUT /v4/clusters/:clusterid/apps/:appname/` https://github.com/giantswarm/api-spec/pull/136
`DELETE /v4/clusters/:clusterid/apps/:appname/` https://github.com/giantswarm/api-spec/pull/137
Towards: https://github.com/giantswarm/giantswarm/issues/4848

Add the managed apps topic.

---

definitions.yaml
spec.yaml

This specs the `PUT /v4/clusters/{cluster_id}/apps/{app_name}/config/` endpoint
~This would be the first endpoint takes a file as its parameter instead of JSON in the body.~
This endpoint takes JSON as normal.
Will be merged into: https://github.com/giantswarm/api-spec/pull/143

Create app config.

---

definitions.yaml

@wind0r reported this typo in our spec

fix typo in cluster_creation_duration p25

---

definitions.yaml
spec.yaml

This adds a way for API users to associate their app with one of the configmaps they can create using the endpoints we're introducing here: https://github.com/giantswarm/api-spec/pull/143

Add user_config to app creation and listing.

---

spec/definitions.yaml
spec/spec.yaml

This PR collects accepted PR's related to app configuration.
**New Endpoints:**
`GET /v4/clusters/{cluster_id}/apps/{app_name}/config/` - https://github.com/giantswarm/api-spec/pull/144
`PUT /v4/clusters/{cluster_id/apps/{app_name}/config/` - https://github.com/giantswarm/api-spec/pull/145
`DELETE /v4/clusters/{cluster_id/apps/{app_name}/config/` - https://github.com/giantswarm/api-spec/pull/150
**Changed Endpoints:**
`GET & PUT /v4/clusters/{cluster_id/apps/{app_name}/` adds the `user_config` key https://github.com/giantswarm/api-spec/pull/147 
Towards: giantswarm/giantswarm#4848

App Configuration Specs

---

Dockerfile
Makefile
README.md
spec/spec.yaml

This PR adds the capability to hide some endpoints which are not ready for use. It applies this to all node-pool specific endpoints.

Hide new endpoints

---

.circleci/config.yml

There's a weird problem currently where this repo sometimes fails to build.
After some googling, I found that doing any apt-get steps first might be a way to mitigate this.

Update before checkout.

---

Dockerfile
docserver/nginx.conf

Change base image to nginxinc/nginx-unprivileged:1.16-alpine

Change base image for unprivileged

---

spec/spec.yaml

For https://github.com/giantswarm/giantswarm/issues/7075
This PR should reveal everything we have hidden so far regarding node pools.

Unhide node pools stuff, fix descriptions

---

docserver/index.html

For https://github.com/giantswarm/giantswarm/issues/7349

Use icons from web-assets, not from giantswarm.io

---

.circleci/config.yml
helm/api-spec-app/Chart.yaml
helm/api-spec-app/templates/deployment.yaml
helm/api-spec-app/templates/psp-rbac.yaml
helm/api-spec-app/templates/service.yaml
helm/api-spec-app/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/7349

App chart fixes/improvements for api-spec

---

details/RESPONSE_CODES.md
spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/9856
This adds spec and info for the 503 response in the addKeyPair operation.

Add spec and info for the 503 response in the addKeyPair operation

---

spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/2918
In case you request a number of workers that is too large.

Add 429 error for requesting a scale that is too large

---

spec/spec.yaml

Got a lil bit carried away by the 429 story 😬

Convert 429 error to 400

---

spec/spec.yaml

Change scaling example to state 'invalid input'

---

spec/spec.yaml

towards: https://github.com/giantswarm/giantswarm/issues/7580

Clarify app name

---

spec/definitions.yaml

Add Azure spec to node pool creation

---

.circleci/config.yml

According to https://gigantic.slack.com/archives/C04TGHDEF/p1595343959309300

Update architect installation in CircleCI config

---

spec/definitions.yaml

Towards https://github.com/giantswarm/giantswarm/issues/12860

azure v5: mention support for setting the AZ count to '-1'

---

spec/definitions.yaml

Allow set min nodepool to 0

---

spec/definitions.yaml

Towards https://github.com/giantswarm/roadmap/issues/234

Fix Scaling cluster response to scale nodepools to 0

---

helm/api-spec-app/templates/deployment.yaml

Adding a missing bit in the deployment

Add resource request and limit

---

spec/definitions.yaml

Towards https://github.com/giantswarm/giantswarm/issues/15310

Use -1 as default price for spot instances max price

---

helm/api-spec-app/templates/psp.yaml
helm/api-spec-app/templates/sa.yaml

Towards https://github.com/giantswarm/giantswarm/issues/29470

Create ServiceAccount even if PSPs are not rendered

---

helm/api-spec-app/templates/deployment.yaml
helm/api-spec-app/values.yaml

Towards
- https://github.com/giantswarm/giantswarm/issues/30255
This PR reduces the CPU and Memory requests and limits and also will allow overriding this value via user values.

Lower resource requests and limits, make them configurable
