giantswarm/api-spec

RESPONSE_CODES.md

This PR extends the list of available response codes within the API. Here I took the freedom to suggest another format of documentation. I would say it is good enough to have a table with the actual code and a broad description of what it means. The details should be covered in the corresponding API documentation. So the docs to the response codes is only the about the actual code and its purpose. IMO we do not need to list all routes in the documentation about response codes.

added table with more response codes

---

.gitignore
Makefile
README.md
circle.yml
definitions.yaml
parameters.yaml
spec.yaml
yamllint/config.yaml

- `parameters.yaml` was missing a parent key at the beginning of the file, which has been added. References were updated. Also, unused items were deleted.
- To validate the concatenated spec YAML, a Makefile with `make validate` (for local use) and `make test` (for CircleCI use) has been introduced.

Fixes in YAML structure; Adding validation tools

---

definitions.yaml
details/RESPONSE_CODES.md
spec.yaml

This specifies what kind of errors our Cluster endpoints will return, as this is not yet specified.
In a nutshell: I think the API should return 401 when the user tries to create a cluster but the organization does not exist or the user is not a member of the organization. (As is already implemented)
However, for the GET, DELETE, and PATCH requests I would expect the API to return a 404, even when the cluster actually exists, but the user simply can't act on it because he is not a member of the organization.
The reasoning behind this difference is that in the 'CREATE' case, we are not acting on something that exists yet, so it doesn't make sense to return a 404. 
In the case of GET, DELETE, and PATCH, the user is providing a `cluster_id` and wants to act on something that he thinks is …

Add more details to possible cluster error responses

---

spec.yaml

The admin user hasn't been given much love in v4 yet. For organization delete, the admin should be able to delete any org. This PR adds that 'rule' the spec.
There is no need to talk about the admin user in the create org part, because creating an org should behave the same way for normal users as well as admin users.

Specify that admin users are able to delete any orgs

---

spec.yaml

Noticed we don't have this yet in /v4/. I need it to check the result of my `add / remove` members PATCH.
My goal is to avoid writing any steps in testbot that use non v4 routes. So while writing tests for `PATCH /v4/organizations/{organization_id}/` I realised I'm going to need `GET /v4/organizations/{organization_id}/`

Spec GET /v4/organizations/{organization_id}/

---

definitions.yaml
spec.yaml

This adds the spec for `GET /v4/clusters/`.
Minor changed in the definition of `V4GenericResponse` to improve the readability in the rendered HTML docs.
**To be merged after implementation**

Spec for GET /v4/clusters/

---

details/RESPONSE_CODES.md
parameters.yaml
spec.yaml

Discussed here: https://github.com/giantswarm/api-spec/issues/29
I think there are a few more things to discuss though:
**1. What to do when the request is invalid?**
Currently I have specced it so that the entire patch operation fails. So if a member is being added that doesn't exist, or has an invalid email address, no  add/remove of members will happen at all, even if there might be other members in the patch request that are valid. Do we agree this is the right way to go about it? An alternative would be to just ignore invalid input.
**2. I think we need a new giant swarm response code:**
We have `UNKNOWN_ATTRIBUTE` and `IMMUTABLE_ATTRIBUTE` but that doesn't really match with what is going wrong here. What do you think of `INVALID_INPUT` with a http error code of `400` ?
ping @marians

Spec for PATCH /v4/organizations/:org-id/

---

.gitignore
definitions.yaml
details/CLUSTER_DEFINITION.md
spec.yaml

**To be merged when implemented**
This PR applies the same changes as https://github.com/giantswarm/api-spec/pull/27, but this time, it should remain unmerged until ready.
TODO

Spec for scaling clusters

---

docserver/index.html
spec.yaml

We had a parser error in our spec. It got only picked up by redoc, the web renderer.

Fix type, add charset meta tag

---

definitions.yaml
spec.yaml

Pretty straightforward. Renaming clusters is just a matter of adding the `name` field to the already existing `PATCH` request for modifying clusters.
Issue: https://github.com/giantswarm/giantswarm/issues/870

Spec a way to rename clusters

---

definitions.yaml
docserver/index.html
spec.yaml

@puja, @marians, and I discussed this last Thursday, that it was becoming important in the short term to be able to set the Common Name of certificates we generate during key pair creation. Since it allows for setting more granular RBAC permissions per certificate instead of granting full admin rights each time.
This PR proposes a way to achieve that for the end user.
Implementation considerations:
We want to allow only a prefix of the Common Name of the certificate to be defined by the user. This lets us avoid collisions with other k8s components, as well as ensures users won't be able to make certificates that have no chance of working, since the K8s API will reject certificates that aren't a subdomain of the clusterdomain.
To avoid collisions with other k8s components, user …

Add cn_prefix and o to keypair requests (RBAC)

---

definitions.yaml

Cluster service stores the final common name, not just the prefix that the user supplied.
This PR corrects that in the spec.

Fix wrong attribute name in the spec

---

parameters.yaml
spec.yaml

Since idempotency is currently not supported techincally, we are removing all according content from the spec/docs.

api-spec: Removing idempotency feature

---

definitions.yaml
parameters.yaml
spec.yaml

Part of https://github.com/giantswarm/giantswarm/issues/2022
This spec change introduces an endpoint that allows the API to inform users/clients which versions of guest cluster software/config are available both for creation of new guest clusters and for upgrades of existing guest clusters.
Status: Will be merged when implemented

Releases endpoint API spec

---

definitions.yaml
spec.yaml

I want a way to create users in the new /v4/ paradigm. This will let me add validations and sanitization that are missing currently at the v1 endpoint.
It also lets us get closer to a point where we can remove all legacy from api, which is something I really want to do.
I know we intend to replace user management entirely in the short/medium term, but I don't want to have any more tech debt and confusion caused by things we know but are not fixing.

Spec creating users

---

spec.yaml

The API in fact returns 201, which is the right thing to do, in case of success after the PUT request.

Fixing success status code for createUser

---

spec.yaml

This PR adds a missing `security` top level section to the spec which references the securityDefinition we have. This is required so that generated clients provide an authentication mechanism.
This is required by https://github.com/giantswarm/giantswarm-js-client/pull/46
As a cleanup, it also renames the securityDefinition from `AuthorizationHeaderToken` to `token_auth`.

Renaming securityDefinition, adding security section

---

definitions.yaml

swagger-codegen was not generating the models for V4Metrics or the PortMappings. 
"Dereferencing" them as is done in this PR allowed the client to be generated properly.
Related: https://github.com/giantswarm/giantswarm-js-client/pull/48

Dereference nested items so that swagger-codegen works.

---

Dockerfile
docserver/index.html

This avoids relying on ReDoc being available at runtime and also reduced the amount of third party tracking. See https://github.com/giantswarm/giantswarm/issues/3232

Include ReDoc JS file in docker image

---

definitions.yaml
spec.yaml

Towards
- https://github.com/giantswarm/giantswarm/issues/2944
- https://github.com/giantswarm/giantswarm/issues/2652 (epic)
This PR adds the spec for a `addCredentials` operation that allows to set the provider credentials for an organization.
For an AWS installation and an organization named `acme`, this is how credentials could be specified:
```nohighlight
curl -X POST -H "Authorization: giantswarm $TOKEN" $API_ENDPOINT/v4/organizations/acme/credentials/ -d '
{
"provider": "aws",
"aws": {
"roles": {
"admin": "arn:aws:iam::123456789012:role/GiantSwarmAdmin",
"awsoperator": "arn:aws:iam::123456789012:role/GiantSwarmAWSOperator"
}
}
}'
```
Response:
```nohighlight
HTTP/1.1 201 Created
Location: /v4/organizations/acme/credentials/abc123/
Content-type: application/json
{
"code": …
```

Add addCredentials operation

---

definitions.yaml

For https://github.com/giantswarm/giantswarm/issues/3449
This fixes a problem with a wrong type definition (int vs. number) and also makes it more explicit in the description that here, both an integer and a floating point value can occur.

Fix type of storage.size_gb and clarify description

---

spec.yaml

Solves https://github.com/giantswarm/giantswarm/issues/3619
This should add request examples to all operations that have a request body.
Note:
The `x-examples` key is a vendor extension introduced by ReDoc, the tool we use for rendering our docs. Swagger/OpenAPI 2.0 does not yet support request examples. This solves a problem we had with request examples being auto-generated and pretty much meaningless.
Also made the displayed `size_gb` value in an example a float instead of an integer, to show that floating point values might occur.
In addition, renamed tag `auth-tokens` to `auth tokens`, to align with `key pairs`.

Add request examples for API docs, improve examples usability

---

definitions.yaml
spec.yaml

For https://github.com/giantswarm/api/issues/475
It seems like vault's PKI implementation requires the entire CN to be a valid domain name (in terms of the character set used). I tested this myself, as I couldn't get a source for the actual validation in place.

Document cn_prefix charset in API spec

---

Makefile
responses.yaml
spec.yaml

Related to https://github.com/giantswarm/gsctl/pull/251
This PR ensures that there is a 401 response defined for every operation. It uses referenes to one generic example for that.
Rationale is that this allows the new client to operate in a consistent way accross all operations. The code generated by go-swagger is different, depending on whether a response is defined or not. To have it consistent we could either have no specific responses anywhere and use the "default" for anything other than 200 (which is bad from a documentation point of view) or have every specific response specified.
Expect more of these PRs the near future.

Add 401 responses everywhere

---

parameters.yaml
spec.yaml

Turns out that the Authorization header spec was missing for the new generated client.

Add Authorization header everywhere

---

spec.yaml

I made a mistake here in https://github.com/giantswarm/api-spec/pull/98 as the createAuthToken operation of course cannot accept an `Authorization` header.

Remove Authorization header from createAuthToken

---

definitions.yaml
spec.yaml

This PR adds a spec for PATCH to our user resource endpoint.
~PATCH `/v4/user/`:~
~Allows someone to modify their own e-mail address.~
PATCH `/v4/users/:email/`:
Allows to modify a given user's e-mail address and/or their expiry date. Only admins are able to edit accounts that don't belong to them, as well as the expiry date.

Add patch user endpoint

---

Makefile

This adds go-swagger validation, which catches more problems than the previous method alone did.

Add validation with go-swagger

---

definitions.yaml
details/CLUSTER_DEFINITION.md
spec.yaml

this attribute was never used/implemented properly and has been
superseded by the `release_version` which combines kubernetes versions
with versions of our operators and other services that are used within a
cluster.
See: https://docs.giantswarm.io/api/#tag/releases

remove kubernetes_version attribute

---

docserver/index.html

This adds a shortcut icon and more to the API spec HTML output, using the same ones we have in the documentation site.

Add icons to HTML

---

Makefile
definitions.yaml
parameters.yaml
spec.yaml

For https://github.com/giantswarm/giantswarm/issues/3987
This PR adds functions to fetch details about the credentials in use for a cluster in AWS or Azure.
- `getCluster` (`GET /v4/clusters/{cluster_id}/`) response now also contains the `credentials_id` key
- new operation `getCredentials` (`GET /v4/organizations/{organization_id}/credentials/`) to fetch credentials of an organization
- new operation `getCredential` (`GET /v4/organizations/{organization_id}/credentials/{credentials_id}/`) to fetch credentials

Expose BYOC credential details

---

spec.yaml

This bit me earlier, it should be documented.
becoming:

Adds note to AuthorizationHeaderToken about SSO

---

definitions.yaml
spec.yaml

clusters can have multiple availability zones now. to get a better
understanding on how this affects subnet ranges and cluster sizes the
info endpoint provides a bit more information about the configured ip
ranges in the installation. clients can then calculate the number of
nodes for the users.

add availability zones

---

definitions.yaml
details/CLUSTER_DEFINITION.md
spec.yaml

respond with the actual list of availability zones of a cluster.

add availability zone to cluster details and listing

---

definitions.yaml

This adds an info how a missing `scalin.min` or `scaling.max` value will be treated.
From https://gigantic.slack.com/archives/C7865GLSY/p1547111558000800

Add info regarding scaling min=max

---

spec.yaml

Towards: [giantswarm/giantswarm#5117](https://github.com/giantswarm/giantswarm/issues/5117)
Follow up: https://github.com/giantswarm/api/pull/711
Add the new `HTTP 409` error for organization delete.

Add delete organization HTTP 409 error

---

yamllint/config.yaml

This increases the line length limit from 80 to 120 characters.
80 is very limiting and sometimes not achievable when there are e. g. URLs in a line.
As a result, we currently get far less warnings, which makes actual errors easier to find and maybe increases the likelihood that warnings are mitigated, too.

Reduce yamllint warnings

---

definitions.yaml
spec.yaml

This PR proposes a way to fetch the apps that are installed on a given tenant cluster.
FYI @giantswarm/sig-ux : Operations can have multiple tags, so it will show up in the `Cluster` category as well as the `App Katalog` category in api docs.
That seems desirable to me since I would personally expect to see it in both places. But opinions are welcome here.

List tenant cluster apps.

---

docserver/index.html

This adds importing webfonts, which we were trying to use so far, but weren't added to the page.
Also adds a little improvement on the rendering of attribute names

Import webfonts, apply Inconsolata to attribute names

---

definitions.yaml

Fixes the `V4AppCatalogsResponse` schema.
Unfortunately, our `validate` step in CI didn't catch this. We'll have to improve that, too.

Fix V4AppCatalogsResponse schema

---

definitions.yaml
spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/6005
This enables the API to expose statistical informtion regarding the installation via the `GET /v4/info/` endpoint.
The only statistic currently supported is `cluster_creation_duration`, which is the duration of cluster ceation, in seconds.

Add stats to info response

---

definitions.yaml
spec.yaml

Hey @giantswarm/team-batman @giantswarm/sig-ux 
I'm implementing a way to upload a values.yaml file for an app so that users can configure their app.
The AppCR spec has a reference to a configmap by name. This can be any name. That means at first sight an endpoint like `/v4/clusters/{cluster_id}/configs/{config_name}/` is the way to go. 
However that has some disadvantages. Instead I am going with `/v4/clusters/{cluster_id}/apps/{app_name}/config/`. 
In this endpoint the configmap does not get a user definable name, even though, using kubectl, a user could create a configmap for the purposes of app configuration and give it whatever name they please.
The idea here is that on `POST` when a user uses the API to create such a configmap, the name will follow a strict convention. However on …

Get app config

---

spec/spec.yaml

This adds two required path parameters and removes one form the `deleteClusterAppConfig` operation.

Fixes a validation problem in deleteClusterAppConfig

---

spec/definitions.yaml
spec/spec.yaml

To be merged into #130 
This is a change we discussed to not use a separate endpoint for clusters status, instead let the cluster details endpoint return the status into, too.

Combine details and status for v5 clusters

---

spec/definitions.yaml
spec/spec.yaml

This is a spec for the PATCH requests on the `app` and `app config` resources.
I made it so only the `user_config` and `version` fields of `app` are editable. I feel like changing the catalog, name, or namespace would probably be complex, not sure how the operators would react to that.
For the `app config`, as long as the configmap is named in the conventional way, users can change anything, using JSON merge patch semantics.

Add spec for modifying apps and app configs.

---

spec/definitions.yaml
spec/spec.yaml

Based on and to be merged into #130 (node-pools)
I found that so far we haven't integrated the following node pool info into the spec
- nodes and nodes ready
Also it would be practical to have all node pools details available when listing node pools for a cluster. So adding the following details to the response:
- nodes and nodes ready
- volume sizes

Adding node spec and status info

---

spec/definitions.yaml
spec/spec.yaml

Fields to be validated
---
| Field | Optional | Validation |
| ---- | --- | --- |
| NodePool Name | True | Length 0-100, block control characters |
| NodePool Scaling | True | `max >= min >= 1`. Default to 3 min max if both empty. Default to 3 min, if max provided > 3 |
| Availability Zones | - | Only one of `number` or `zones` |
| Availability Zones - `number` | True | `installations max >= number >= 1` (Check with Tuomas).  Default to 1 if no names nor numbers given |
| Availability Zones - `zones` | True | Regexp to validate name format `a-z, -, 0-9`. Validate against cluster region |
| Node Spec AWS Instance Type | True | Validate against info instance type list |
Invalid requests to return `400 Bad Request` with description of validation error

Node Pool Creation Validation

---

spec/definitions.yaml
spec/spec.yaml

This adds the labels on an `app catalog CR` to the `get catalogs` api endpoint output.

Add catalog-type labels

---

spec/definitions.yaml
spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/5465
This PR adds an attribute to the `GET /v4/info/` response that will allow clients to detect from which release version on support for node pools will be available.

Add features section to info response

---

spec/parameters.yaml
spec/spec.yaml

An experiment to see if we are actually doing this the right way.
I think we already define the security / auth method in a previous part of the spec. 
Instead of being able to just have an instance of the API client and set the token once, having it in every request as a required header param forces us to pass it in as a param on _every_ call, which makes the state handling of the token a bit more complex in Happa, especially when the token refreshes every 5 minutes.

Remove required auth header.

---

spec/definitions.yaml
spec/spec.yaml

This adds CRUD endpoints at `/v4/clusters/{cluster_id}/apps/{app_name}/secret/`
@rossf7 and others, are there any decisions made yet regarding the conventional name for the user config secret?
Like how the configmap should be called `{app-name}-user-values`.
What should / will the secret be called?

Add secret CRUD endpoints to api-spec.

---

spec/definitions.yaml
spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/5465
As detailed in https://github.com/giantswarm/giantswarm/issues/5465#issuecomment-528360513 we decided to simplify v5 cluster creation, removing the possibility to define node pools in the same request.

Remove nodepools from addClusterV5 request body

---

spec/definitions.yaml
spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/7105
This PR adds the capability to let the info endpoint (`GET /v4/info/`) inform about the distinct availability zone names usable in a region.

Add availability zone names to info endpoint response

---

spec/spec.yaml

This adds a missing default case to the  `addKeyPair` operation and should simplify error handling in clients.

Add default case to addKeyPair operation

---

details/RESPONSE_CODES.md

This adds a new code to be used e. g. if the given operation is not supported on a certain provider.

Add NOT_SUPPORTED error code

---

.circleci/config.yml

Cleaning up the CI config, avoiding waste of time and resources

Remove yamllint installation step from CircleCI config

---

Makefile

We use v0.19.0 in gsclientgen, so we should use that version here, at least, for validation.

Update goswagger version used for validation

---

spec/spec.yaml

There was a letter missing in the media type of some examples.

Fix typo in examples media type

---

details/RESPONSE_CODES.md

Adding the so far undocumented error code `INTERNAL_ERROR` which is already in use.

Add INTERNAL_ERROR to response codes

---

Makefile
README.md

To simplify API testing we are exploring the use of https://github.com/stoplightio/prism which creates a mock service based on the spec.
Run `make mock`.
gsctl
Server log

Add 'make mock' command to enable running a prism mock server

---

spec/definitions.yaml

API spec draft for https://github.com/giantswarm/giantswarm/issues/7516
The idea is to have deleted clusters appear
- in the `GET /v4/clusters/` response
- in the `GET /v4/clusters/{cluster_id}/` response
- in the `GET /v5/clusters/{cluster_id}/` response
as long as they are not fully deleted. The `delete_date` value should represent the date when deletion of the cluster has been requested.

Add delete_date attribute

---

spec/definitions.yaml
spec/spec.yaml

This adds `labels` to the Apps response.
The idea would be to include labels like:
```
app: chart-operator
app-operator.giantswarm.io/version: 1.0.0
giantswarm.io/cluster: pbd2x
giantswarm.io/managed-by: cluster-operator
giantswarm.io/organization: giantswarm
giantswarm.io/service-type: managed
```
In the API response so that UI's can figure out whether or not the App was preinstalled 
Is: `managed-by: cluster-operator` a guaranteed 'preinstalled' app?
Do we need a new label to make this more explicit?
ping @puja108 @rossf7 
I got those labels from a cluster on ginger:  `kubectl get apps -n pbd2x chart-operator -o yaml`

Add app labels

---

spec/spec.yaml

This adds the family of `v5/clusters/{cluster_id}/apps` endpoints to the spec, which are being implemented here: https://github.com/giantswarm/api/pull/965

Add v5 app endpoints

---

.circleci/config.yml
helm/api-spec-app/Chart.yaml
helm/api-spec-app/templates/deployment.yaml
helm/api-spec-app/templates/psp-rbac.yaml
helm/api-spec-app/templates/service.yaml
helm/api-spec-app/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/7349
**This PR does not contain any changes regarding the Giant Swarm API specification. The focus is on the technicalities of publishing the documentation.**
This PR should enable the app to use an EmptyDir volume for the nginx cache. It's derived from the working docs deployment in gollum/35ac3.

Add ServiceAccount, Role, RoleBinding, and PSP for using EmptyDir

---

spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/3046
This adds a 400 status code error in case the provided instance type while creating a cluster is not supported.

Add 400 error for invalid instance type

---

spec/definitions.yaml
spec/spec.yaml

Follow-up to #196 
Improvements over #196:
- Adds the usual header parameters to `getClusterLabels` & `setClusterLabels`
- Adds separate Request definition. Right now Request & Response share one definition which is confusing in generated clients IMO
- Renaming of `V5ListClustersByLabel` to make it clear it is a Request definition

Fix some mistakes of the original cluster labelling PR

---

spec/definitions.yaml

`x-nullable: true` is required to allow go json marshalling with strings and `null`. Thanks @tfussell for the pointer!

Make labels for label change requests nullable

---

spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/3823
Converted the existing 400 error to 409, and created a new 400 error for invalid input.

Convert 400 error content to 409 and keep 400 error for invalid input

---

spec/definitions.yaml
spec/spec.yaml

A customer got a bit confused about the `user_config` not being editable, and thinking that meant that config in general was not editable. I tried to explain that better.
I also aligned the capitalization of ConfigMap throughout the descriptions in the spec.

Align ConfigMap case, explain user_config editing.

---

spec/definitions.yaml
spec/spec.yaml

For [HA Masters](https://github.com/giantswarm/roadmap/issues/58). Closes https://github.com/giantswarm/giantswarm/issues/7901
- For v5 cluster creation, the `master` property gets deprecated, to be replaced by the new `master_nodes` property. There will be a deprecation phase where the old form can still be used to create clusters with single master nodes.
- For getting v5 cluster details, likewise the `master` property gets deprecated, eventually to be replaced by the new `master_nodes` property. During the deprecation phase, both properties will be served in case the cluster has only one master node.
- The `modifyClusterV5` request body is changed to support the switch from single to HA masters.

Update spec for master nodes high availability

---

.circleci/config.yml
spec/definitions.yaml

Towards https://github.com/giantswarm/roadmap/issues/9.
What's in the box:
- Adding Azure-specific fields to the API response when listing node pools

Add Azure specific fields to V5GetNodePoolResponseNodeSpec

---

spec/definitions.yaml

Towards https://github.com/giantswarm/giantswarm/issues/12567
This PR makes the release status required, so it won't be annotated as `omitempty` in the generated `gsclientgen` data structure.

Make release status required

---

spec/spec.yaml

Closes https://github.com/giantswarm/giantswarm/issues/12723
Indicate which endpoint version must be used, in relation to the cluster release version.

Mention which endpoint version to use for certain release versions / providers

---

spec/spec.yaml

Analog of https://github.com/giantswarm/api/pull/1123

azure v5: change first node pools version to 13.0.0

---

spec/definitions.yaml
spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/13439
Add new `supported_k8s_version_skews` property in the info response, for displaying the supported K8s versions. Versions older than the ones specified are EOL and should not be used for new clusters.
This PR will be merged once the API implementation is done and released.

Add property for supported K8s versions in the info response

---

spec/definitions.yaml

Towards giantswarm/giantswarm#12489
This changes the description text of the `active` field of release response items to make it clear that cluster creation is possible but not recommended.

document cluster creation possible with deprecated versions

---

spec/definitions.yaml
spec/spec.yaml

Towards https://github.com/giantswarm/giantswarm/issues/14961

Terminology changes: "tenant cluster" to "workload cluster", "control plane" to "management cluster"

---

spec/spec.yaml

This mention is no longer the case, and unnecessary, in my opinion. What do you think?

Remove the unnecessary mention of the V5 API being supported by AWS only

---

spec/definitions.yaml

Towards https://github.com/giantswarm/giantswarm/issues/15310
This PR adds configuration settings for Azure Spot Instances:
* Node pool creation:
* Enabling or disabling the feature
* Setting a maximum price for deallocating the node pool (or disabling deallocating based on pricing reasons)
* Node pool listing/searching:
* Seeing if the feature is enabled or not
* Seeing the maximum price for deallocating the node pool (or the lack of it)

Add properties regarding azure spot instances

---

.circleci/config.yml
helm/api-spec-app/Chart.yaml
spec/spec.yaml

Updates the catalog domain to giantswarm.github.io instead of giantswarm.github.com. Towards giantswarm/giantswarm#15898
Also updates the architect-orb version to 2.7.0 to resolve pushing into catalogs

Update catalog domain to github.io and update architect-orb to 2.7.0

---

.circleci/config.yml

The goal of this PR is to make sure that the workflow also runs on tagged releases.

CircleCI: also lint on tags
